name: Deploy Moodle to Azure

on:
  push:
    branches:
      - main   # Bei jedem Push auf main-Branch deployen

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Schritt 1: Code aus dem Repository holen
      - uses: actions/checkout@v3

      # Schritt 2: Optional Composer-Dependencies installieren
      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader || true

      # Schritt 3: Moodle in ein ZIP-Paket packen
      - name: Create zip package
        run: zip -r moodle.zip . -x "*.git*"

      # Schritt 4: Deployment zu Azure App Service
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: moodle    # Name deiner Azure Web App
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: moodle.zip
